// SPDX-License-Identifier: AGPL-3.0-or-later

// Copyright (C) 2026 ShinKouyo <i@0x0f.dev>
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

package repo

import (
	"bytes"
	"context"
	"fmt"
	"io"
	"os"
	"strings"
	"time"
)

// repoDBName returns the canonical pacman database file name of the
// configured repository ("<name>.db", e.g. "varve.db"). pacman clients
// consume this name; on disk it exists as a symlink to the gzip archive
// <name>.db.tar.gz that repo-add generates. The s3 flow stores it as an
// object carrying the archive bytes.
func (u *updater) repoDBName() string {
	return u.cfg.Repo.Name + ".db"
}

// repoDBArchiveName returns the gzip database archive generated by
// repo-add ("<name>.db.tar.gz"). It is the repo-add/repo-remove command
// argument and the target of the <name>.db symlink; the s3 flow uploads it
// next to the <name>.db object, both holding the archive bytes.
func (u *updater) repoDBArchiveName() string {
	return u.cfg.Repo.Name + ".db.tar.gz"
}

// repoFilesDBName returns the canonical file database file name of the
// configured repository ("<name>.files"). pacman clients consume it
// alongside <name>.db; like the database it is a symlink to the gzip
// archive <name>.files.tar.gz generated by repo-add.
func (u *updater) repoFilesDBName() string {
	return u.cfg.Repo.Name + ".files"
}

// repoFilesDBArchiveName returns the gzip file database archive generated
// by repo-add ("<name>.files.tar.gz"), a sibling of the database archive.
func (u *updater) repoFilesDBArchiveName() string {
	return u.cfg.Repo.Name + ".files.tar.gz"
}

// repoUpdateLocal updates the pacman database directly on the local
// repository root: replaced pkgnames are removed first, then all new
// package files are added (remove-before-add).
func (u *updater) repoUpdateLocal(ctx context.Context, removed []string, pkgs []Artifact) error {
	dir := u.cfg.Storage.Local.Root
	for _, name := range removed {
		if err := u.runRepoRemove(ctx, dir, name); err != nil {
			return err
		}
	}
	return u.runRepoAdd(ctx, dir, packageFiles(pkgs))
}

// runRepoAdd executes repo-add <archive> <package...> in dir. The .db.tar.gz
// archive name is what repo-add accepts; it derives <name>.db / <name>.files
// from it.
func (u *updater) runRepoAdd(ctx context.Context, dir string, files []string) error {
	args := append([]string{u.repoDBArchiveName()}, files...)
	return u.runRepoCmd(ctx, "repo-add", dir, args...)
}

// runRepoRemove executes repo-remove <archive> <pkgname> in dir.
func (u *updater) runRepoRemove(ctx context.Context, dir, pkgname string) error {
	return u.runRepoCmd(ctx, "repo-remove", dir, u.repoDBArchiveName(), pkgname)
}

// repoCmdTimeout bounds one repo-add/repo-remove subprocess. The exec
// already inherits the caller's context, but that context carries no
// deadline (the API server sets none): a hung repo-add would otherwise
// hold the ingest mutex (and the HTTP handler behind Caddy) open until the
// client gives up. It is a variable so tests can shorten it.
var repoCmdTimeout = 5 * time.Minute

// runRepoCmd runs one external pacman database command. With
// repo.sign == "packages+db" the command receives --sign and the signer's
// GNUPGHOME environment fragment. A non-zero exit is reported as an error
// whose summary carries the last 200 characters of stderr. The subprocess
// is bounded by repoCmdTimeout on top of ctx.
func (u *updater) runRepoCmd(ctx context.Context, name, dir string, args ...string) error {
	full := []string{name}
	if u.signDB() {
		full = append(full, "--sign")
	}
	full = append(full, args...)
	cmdCtx, cancel := context.WithTimeout(ctx, repoCmdTimeout)
	defer cancel()
	cmd := u.execCommand(cmdCtx, full[0], full[1:]...)
	cmd.Dir = dir
	if u.signDB() && u.signer != nil {
		env := cmd.Env
		if env == nil {
			env = os.Environ()
		}
		cmd.Env = append(env, u.signer.GnuPGEnv()...)
	}
	var stderr bytes.Buffer
	cmd.Stdout = io.Discard
	cmd.Stderr = &stderr
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("%s: %w: %s", strings.Join(full, " "), err, stderrTail(stderr.String()))
	}
	return nil
}

// signDB reports whether the repository database must be signed.
func (u *updater) signDB() bool {
	return u.cfg.Repo.Sign == "packages+db"
}

// packageFiles returns the file names of the package artifacts.
func packageFiles(pkgs []Artifact) []string {
	out := make([]string, 0, len(pkgs))
	for _, p := range pkgs {
		out = append(out, p.File)
	}
	return out
}

// stderrTail returns the last n characters of s (the full text when
// shorter), used for the error summary of a failed external command.
func stderrTail(s string) string {
	const n = 200
	if len(s) <= n {
		return s
	}
	return s[len(s)-n:]
}
