# SPDX-License-Identifier: AGPL-3.0-or-later
#
# Copyright (C) 2026 ShinKouyo <i@0x0f.dev>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Controller image for the varve management machine (PURPOSAL 5.5,
# DESIGN 9.2). Runs the varve binary against the /data volume.

FROM archlinux/archlinux:latest

# The base image ships no package database: refresh it before
# installing anything.
RUN pacman -Sy --noconfirm

# git: pull source repositories; subversion: query SVN upstream revisions;
# gnupg: key hosting and per-task injection. repo-add/repo-remove ship
# with the pacman package already present in the base image.
RUN pacman -S --noconfirm git subversion gnupg

# Controller binary. Build it beforehand with `go build ./cmd/varve`.
COPY varve /usr/bin/varve

VOLUME /data

# worker API (31759) and Web UI (31760).
EXPOSE 31759 31760

ENTRYPOINT ["varve"]
